server:
    port: 8099
spring
    h2:
        console:
            enable: true
            path: /test_db
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:~/Develop/Github/SpringBlogExam/test_db;AUTO_SERVER=TRUE
        username: test
        password: 1234
