server:
    port: 8080
mybatis:
    type-aliases-package: com.study.hsy.model
    mapper-locations: mybatis/*.xml
spring:
    h2:
        console:
            enable: true
            path: /db
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:~/Develop/Github/SpringBlogExam/test_db;AUTO_SERVER=TRUE
        username: test
        password: 1234
